<a href="https://colab.research.google.com/github/dhruvgupta9191/Customer360/blob/main/Customer360.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving data1.csv to data1.csv

In [ ]:
import pandas as pd

In [ ]:
import io

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded['data1.csv']) , header = 0 , encoding = 'unicode_escape')

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom

In [ ]:
import numpy as np

In [ ]:
df['Rating'] = np.random.randint(0,6,df.shape[0])

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom,2
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,4
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom,4
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,5
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,1

In [ ]:
df['used_Discount'] = np.random.randint(0,2,df.shape[0])

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom,2,1
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,4,0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom,4,1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,5,1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,1,1

In [ ]:
df['used_bogo'] = np.where(df['used_Discount'] == 1, 0, 1 )

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom,2,1,0
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,4,0,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom,4,1,0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,5,1,0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,1,1,0

In [ ]:
off=['Buy one get one','No offer','10','15','20','25']

In [ ]:
df["Offer"]=np.random.choice(off,size=df.shape[0])

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo,Offer
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom,2,1,0,15
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,4,0,1,No offer
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom,4,1,0,10
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,5,1,0,Buy one get one
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom,1,1,0,25

In [ ]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo,Offer
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2,1,0,15
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,4,0,1,No offer
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,4,1,0,10
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,5,1,0,Buy one get one
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,1,1,0,25

In [ ]:
df["Day_Name"] = pd.to_datetime(df["InvoiceDate"]).dt.day_name()
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo,Offer,Day_Name
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2,1,0,15,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,4,0,1,No offer,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,4,1,0,10,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,5,1,0,Buy one get one,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,1,1,0,25,Wednesday

In [ ]:
df.shape

(541909, 13)

In [ ]:
df.isnull().sum()

InvoiceNo             0
StockCode             0
Description        1454
Quantity              0
InvoiceDate           0
UnitPrice             0
CustomerID       135080
Country               0
Rating                0
used_Discount         0
used_bogo             0
Offer                 0
Day_Name              0
dtype: int64

In [ ]:
round(100*(df.isnull().sum())/len(df),2)

InvoiceNo         0.00
StockCode         0.00
Description       0.27
Quantity          0.00
InvoiceDate       0.00
UnitPrice         0.00
CustomerID       24.93
Country           0.00
Rating            0.00
used_Discount     0.00
used_bogo         0.00
Offer             0.00
Day_Name          0.00
dtype: float64

In [ ]:
df.dropna(inplace = True)

In [ ]:
round(100*(df.isnull().sum())/len(df),2)

InvoiceNo        0.0
StockCode        0.0
Description      0.0
Quantity         0.0
InvoiceDate      0.0
UnitPrice        0.0
CustomerID       0.0
Country          0.0
Rating           0.0
used_Discount    0.0
used_bogo        0.0
Offer            0.0
Day_Name         0.0
dtype: float64

In [ ]:
df.shape

(406829, 13)

In [ ]:
result=df.dtypes

In [ ]:
result

InvoiceNo                object
StockCode                object
Description              object
Quantity                  int64
InvoiceDate      datetime64[ns]
UnitPrice               float64
CustomerID              float64
Country                  object
Rating                    int64
used_Discount             int64
used_bogo                 int64
Offer                    object
Day_Name                 object
dtype: object

In [ ]:
df['CustomerID'] = df['CustomerID'].astype('int')
df['Rating'] = df['Rating'].astype('int')
df['Quantity'] = df['Quantity'].astype('int')
df['UnitPrice'] = df['UnitPrice'].astype('float')

In [ ]:
df.dtypes

InvoiceNo                object
StockCode                object
Description              object
Quantity                  int64
InvoiceDate      datetime64[ns]
UnitPrice               float64
CustomerID                int64
Country                  object
Rating                    int64
used_Discount             int64
used_bogo                 int64
Offer                    object
Day_Name                 object
dtype: object

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import nltk

from sklearn.neighbors import NearestNeighbors
from sklearn import neighbors
from scipy.spatial.distance import cosine
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score


from sklearn.feature_selection import SelectKBest
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

import re
import string
from wordcloud import WordCloud, STOPWORDS

In [ ]:
count = df.groupby("CustomerID", as_index=False).count()

In [ ]:
count

,CustomerID,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country,Rating,used_Discount,used_bogo,Offer,Day_Name
0,12346,2,2,2,2,2,2,2,2,2,2,2,2
1,12347,182,182,182,182,182,182,182,182,182,182,182,182
2,12348,31,31,31,31,31,31,31,31,31,31,31,31
3,12349,73,73,73,73,73,73,73,73,73,73,73,73
4,12350,17,17,17,17,17,17,17,17,17,17,17,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4367,18280,10,10,10,10,10,10,10,10,10,10,10,10
4368,18281,7,7,7,7,7,7,7,7,7,7,7,7
4369,18282,13,13,13,13,13,13,13,13,13,13,13,13
4370,18283,756,756,756,756,756,756,756,756,756,756,756,756
4371,18287,70,70,70,70,70,70,70,70,70,70,70,70

In [ ]:
mean = df.groupby("CustomerID", as_index=False).mean()
mean

<ipython-input-38-92fc5ad8da29>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mean = df.groupby("CustomerID", as_index=False).mean()

      CustomerID   Quantity  UnitPrice    Rating  used_Discount  used_bogo
0          12346   0.000000   1.040000  3.500000       1.000000   0.000000
1          12347  13.505495   2.644011  2.538462       0.483516   0.516484
2          12348  75.516129   5.764839  3.354839       0.354839   0.645161
3          12349   8.643836   8.289041  2.589041       0.397260   0.602740
4          12350  11.588235   3.841176  2.470588       0.352941   0.647059
...          ...        ...        ...       ...            ...        ...
4367       18280   4.500000   4.765000  2.900000       0.500000   0.500000
4368       18281   7.714286   5.622857  1.428571       0.285714   0.714286
4369       18282   7.538462   4.821538  2.384615       0.538462   0.461538
4370       18283   1.847884   1.614987  2.466931       0.476190   0.523810
4371       18287  22.657143   1.493571  2.757143       0.442857   0.557143

[4372 rows x 6 columns]

In [ ]:
df1 = pd.merge(df, count, how='right', on=["CustomerID"])

In [ ]:
df1

,InvoiceNo_x,StockCode_x,Description_x,Quantity_x,InvoiceDate_x,UnitPrice_x,CustomerID,Country_x,Rating_x,used_Discount_x,...,Description_y,Quantity_y,InvoiceDate_y,UnitPrice_y,Country_y,Rating_y,used_Discount_y,used_bogo_y,Offer_y,Day_Name_y
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom,4,1,...,2,2,2,2,2,2,2,2,2,2
1,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346,United Kingdom,3,1,...,2,2,2,2,2,2,2,2,2,2
2,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347,Iceland,1,0,...,182,182,182,182,182,182,182,182,182,182
3,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347,Iceland,2,1,...,182,182,182,182,182,182,182,182,182,182
4,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347,Iceland,1,0,...,182,182,182,182,182,182,182,182,182,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406824,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287,United Kingdom,4,1,...,70,70,70,70,70,70,70,70,70,70
406825,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287,United Kingdom,0,1,...,70,70,70,70,70,70,70,70,70,70
406826,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287,United Kingdom,3,1,...,70,70,70,70,70,70,70,70,70,70
406827,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287,United Kingdom,3,1,...,70,70,70,70,70,70,70,70,70,70
406828,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287,United Kingdom,1,1,...,70,70,70,70,70,70,70,70,70,70

In [ ]:
df1.rename({'StockCode_y': 'Count'}, axis=1, inplace=True)
df1.rename({'Rating_x': 'Rating'}, axis=1, inplace=True)
df1.rename({'Description_x': 'Description'}, axis=1, inplace=True)

In [ ]:
df1

,InvoiceNo_x,StockCode_x,Description,Quantity_x,InvoiceDate_x,UnitPrice_x,CustomerID,Country_x,Rating,used_Discount_x,...,Description_y,Quantity_y,InvoiceDate_y,UnitPrice_y,Country_y,Rating_y,used_Discount_y,used_bogo_y,Offer_y,Day_Name_y
0,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom,4,1,...,2,2,2,2,2,2,2,2,2,2
1,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346,United Kingdom,3,1,...,2,2,2,2,2,2,2,2,2,2
2,537626,85116,BLACK CANDELABRA T-LIGHT HOLDER,12,2010-12-07 14:57:00,2.10,12347,Iceland,1,0,...,182,182,182,182,182,182,182,182,182,182
3,537626,22375,AIRLINE BAG VINTAGE JET SET BROWN,4,2010-12-07 14:57:00,4.25,12347,Iceland,2,1,...,182,182,182,182,182,182,182,182,182,182
4,537626,71477,COLOUR GLASS. STAR T-LIGHT HOLDER,12,2010-12-07 14:57:00,3.25,12347,Iceland,1,0,...,182,182,182,182,182,182,182,182,182,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406824,570715,22419,LIPSTICK PEN RED,12,2011-10-12 10:23:00,0.42,18287,United Kingdom,4,1,...,70,70,70,70,70,70,70,70,70,70
406825,570715,22866,HAND WARMER SCOTTY DOG DESIGN,12,2011-10-12 10:23:00,2.10,18287,United Kingdom,0,1,...,70,70,70,70,70,70,70,70,70,70
406826,573167,23264,SET OF 3 WOODEN SLEIGH DECORATIONS,36,2011-10-28 09:29:00,1.25,18287,United Kingdom,3,1,...,70,70,70,70,70,70,70,70,70,70
406827,573167,21824,PAINTED METAL STAR WITH HOLLY BELLS,48,2011-10-28 09:29:00,0.39,18287,United Kingdom,3,1,...,70,70,70,70,70,70,70,70,70,70
406828,573167,21014,SWISS CHALET TREE DECORATION,24,2011-10-28 09:29:00,0.29,18287,United Kingdom,1,1,...,70,70,70,70,70,70,70,70,70,70

In [ ]:
df1 = df1[["CustomerID",'Description','Rating',"Count"]]
df1

        CustomerID                          Description  Rating  Count
0            12346       MEDIUM CERAMIC TOP STORAGE JAR       4      2
1            12346       MEDIUM CERAMIC TOP STORAGE JAR       3      2
2            12347      BLACK CANDELABRA T-LIGHT HOLDER       1    182
3            12347    AIRLINE BAG VINTAGE JET SET BROWN       2    182
4            12347    COLOUR GLASS. STAR T-LIGHT HOLDER       1    182
...            ...                                  ...     ...    ...
406824       18287                     LIPSTICK PEN RED       4     70
406825       18287        HAND WARMER SCOTTY DOG DESIGN       0     70
406826       18287   SET OF 3 WOODEN SLEIGH DECORATIONS       3     70
406827       18287  PAINTED METAL STAR WITH HOLLY BELLS       3     70
406828       18287        SWISS CHALET TREE DECORATION        1     70

[406829 rows x 4 columns]

In [ ]:
df1 = df1.sort_values('Count', ascending=False)
df1

        CustomerID                          Description  Rating  Count
377605       17841               EIGHT PIECE SNAKE  SET       3   7983
382239       17841                        CHILLI LIGHTS       5   7983
382245       17841         JINGLE BELL HEART DECORATION       5   7983
382244       17841         POLYESTER FILLER PAD 45x45cm       4   7983
382243       17841     HEART DECORATION RUSTIC HANGING        1   7983
...            ...                                  ...     ...    ...
64577        13256       ASSTD DESIGN 3D PAPER STICKERS       1      1
390841       17986  JUMBO BAG SCANDINAVIAN BLUE PAISLEY       4      1
310226       16881            ASSORTED COLOURS SILK FAN       0      1
241455       15753     AGED GLASS SILVER T-LIGHT HOLDER       1      1
68565        13302  SET OF 16 VINTAGE PISTACHIO CUTLERY       3      1

[406829 rows x 4 columns]

In [ ]:
df2 = df1[df1.Count >= 100]
df2

        CustomerID                       Description  Rating  Count
377605       17841            EIGHT PIECE SNAKE  SET       3   7983
382239       17841                     CHILLI LIGHTS       5   7983
382245       17841      JINGLE BELL HEART DECORATION       5   7983
382244       17841      POLYESTER FILLER PAD 45x45cm       4   7983
382243       17841  HEART DECORATION RUSTIC HANGING        1   7983
...            ...                               ...     ...    ...
2726         12391               HAPPY STENCIL CRAFT       0    100
2725         12391            BALLOONS  WRITING SET        1    100
2724         12391         PARTY TIME PENCIL ERASERS       4    100
218205       15411              DOORMAT BLACK FLOCK        2    100
358888       17614   MAGIC DRAWING SLATE DOLLY GIRL        1    100

[296318 rows x 4 columns]

In [ ]:
df4 = df.groupby("CustomerID", as_index=False).mean()
df4

<ipython-input-46-78615617cc6c>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df4 = df.groupby("CustomerID", as_index=False).mean()

      CustomerID   Quantity  UnitPrice    Rating  used_Discount  used_bogo
0          12346   0.000000   1.040000  3.500000       1.000000   0.000000
1          12347  13.505495   2.644011  2.538462       0.483516   0.516484
2          12348  75.516129   5.764839  3.354839       0.354839   0.645161
3          12349   8.643836   8.289041  2.589041       0.397260   0.602740
4          12350  11.588235   3.841176  2.470588       0.352941   0.647059
...          ...        ...        ...       ...            ...        ...
4367       18280   4.500000   4.765000  2.900000       0.500000   0.500000
4368       18281   7.714286   5.622857  1.428571       0.285714   0.714286
4369       18282   7.538462   4.821538  2.384615       0.538462   0.461538
4370       18283   1.847884   1.614987  2.466931       0.476190   0.523810
4371       18287  22.657143   1.493571  2.757143       0.442857   0.557143

[4372 rows x 6 columns]

In [ ]:
combine_summary = df2.groupby("CustomerID")["Description"].apply(list)
combine_summary

CustomerID
12347    [PINK DRAWER KNOB ACRYLIC EDWARDIAN, GREEN DRA...
12357    [PENNY FARTHING BIRTHDAY CARD, S/4 CACTI CANDL...
12359    [POPPY FIELDS CHOPPING BOARD, WALL ART DOG LIC...
12360    [SET 36 COLOUR PENCILS DOLLY GIRL, SET OF 20 V...
12362    [JUMBO BAG RED RETROSPOT, JUMBO BAG VINTAGE DO...
                               ...
18245    [WRAP COWBOYS  , ALARM CLOCK BAKELIKE RED , SP...
18257    [VINTAGE DOILY TRAVEL SEWING KIT, CHILDRENS CU...
18260    [RED RETROSPOT TEA CUP AND SAUCER , PINK BLUE ...
18272    [SET OF 4 JAM JAR MAGNETS, RED SPOT CERAMIC DR...
18283    [CHARLOTTE BAG PINK POLKADOT, CHARLOTTE BAG SU...
Name: Description, Length: 1115, dtype: object

In [ ]:
combine_summary = pd.DataFrame(combine_summary)
combine_summary

                                                  Description
CustomerID
12347       [PINK DRAWER KNOB ACRYLIC EDWARDIAN, GREEN DRA...
12357       [PENNY FARTHING BIRTHDAY CARD, S/4 CACTI CANDL...
12359       [POPPY FIELDS CHOPPING BOARD, WALL ART DOG LIC...
12360       [SET 36 COLOUR PENCILS DOLLY GIRL, SET OF 20 V...
12362       [JUMBO BAG RED RETROSPOT, JUMBO BAG VINTAGE DO...
...                                                       ...
18245       [WRAP COWBOYS  , ALARM CLOCK BAKELIKE RED , SP...
18257       [VINTAGE DOILY TRAVEL SEWING KIT, CHILDRENS CU...
18260       [RED RETROSPOT TEA CUP AND SAUCER , PINK BLUE ...
18272       [SET OF 4 JAM JAR MAGNETS, RED SPOT CERAMIC DR...
18283       [CHARLOTTE BAG PINK POLKADOT, CHARLOTTE BAG SU...

[1115 rows x 1 columns]

In [ ]:
combine_summary.to_csv("combine_summary.csv")
combine_summary

                                                  Description
CustomerID
12347       [PINK DRAWER KNOB ACRYLIC EDWARDIAN, GREEN DRA...
12357       [PENNY FARTHING BIRTHDAY CARD, S/4 CACTI CANDL...
12359       [POPPY FIELDS CHOPPING BOARD, WALL ART DOG LIC...
12360       [SET 36 COLOUR PENCILS DOLLY GIRL, SET OF 20 V...
12362       [JUMBO BAG RED RETROSPOT, JUMBO BAG VINTAGE DO...
...                                                       ...
18245       [WRAP COWBOYS  , ALARM CLOCK BAKELIKE RED , SP...
18257       [VINTAGE DOILY TRAVEL SEWING KIT, CHILDRENS CU...
18260       [RED RETROSPOT TEA CUP AND SAUCER , PINK BLUE ...
18272       [SET OF 4 JAM JAR MAGNETS, RED SPOT CERAMIC DR...
18283       [CHARLOTTE BAG PINK POLKADOT, CHARLOTTE BAG SU...

[1115 rows x 1 columns]

In [ ]:
df3 = pd.read_csv("combine_summary.csv")

In [ ]:
df3 = pd.merge(df3, df4, on="CustomerID", how='inner')
df3 = df3[['CustomerID','Description','Rating']]
df3

      CustomerID                                        Description    Rating
0          12347  ['PINK DRAWER KNOB ACRYLIC EDWARDIAN', 'GREEN ...  2.538462
1          12357  ['PENNY FARTHING BIRTHDAY CARD', 'S/4 CACTI CA...  2.465649
2          12359  ['POPPY FIELDS CHOPPING BOARD', 'WALL ART DOG ...  2.393701
3          12360  ['SET 36 COLOUR PENCILS DOLLY GIRL', 'SET OF 2...  2.542636
4          12362  ['JUMBO BAG RED RETROSPOT', 'JUMBO BAG VINTAGE...  2.463504
...          ...                                                ...       ...
1110       18245  ['WRAP COWBOYS  ', 'ALARM CLOCK BAKELIKE RED '...  2.451977
1111       18257  ['VINTAGE DOILY TRAVEL SEWING KIT', 'CHILDRENS...  2.341463
1112       18260  ['RED RETROSPOT TEA CUP AND SAUCER ', 'PINK BL...  2.550000
1113       18272  ['SET OF 4 JAM JAR MAGNETS', 'RED SPOT CERAMIC...  2.682353
1114       18283  ['CHARLOTTE BAG PINK POLKADOT', 'CHARLOTTE BAG...  2.466931

[1115 rows x 3 columns]

In [ ]:
cleanup_re = re.compile('[^a-z]+')
cleanup_re

re.compile(r'[^a-z]+', re.UNICODE)

In [ ]:
def cleanup(sentence):
    sentence = sentence.lower()
    sentence = cleanup_re.sub(' ', sentence).strip()
    sentence = " ".join(nltk.word_tokenize(sentence))
    return sentence

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [ ]:
df3["Description_clean"] = df3["Description"].apply(cleanup)
df3

,CustomerID,Description,Rating,Description_clean
0,12347,"['PINK DRAWER KNOB ACRYLIC EDWARDIAN', 'GREEN ...",2.538462,pink drawer knob acrylic edwardian green drawe...
1,12357,"['PENNY FARTHING BIRTHDAY CARD', 'S/4 CACTI CA...",2.465649,penny farthing birthday card s cacti candles f...
2,12359,"['POPPY FIELDS CHOPPING BOARD', 'WALL ART DOG ...",2.393701,poppy fields chopping board wall art dog licen...
3,12360,"['SET 36 COLOUR PENCILS DOLLY GIRL', 'SET OF 2...",2.542636,set colour pencils dolly girl set of vintage c...
4,12362,"['JUMBO BAG RED RETROSPOT', 'JUMBO BAG VINTAGE...",2.463504,jumbo bag red retrospot jumbo bag vintage doil...
...,...,...,...,...
1110,18245,"['WRAP COWBOYS ', 'ALARM CLOCK BAKELIKE RED '...",2.451977,wrap cowboys alarm clock bakelike red spotty b...
1111,18257,"['VINTAGE DOILY TRAVEL SEWING KIT', 'CHILDRENS...",2.341463,vintage doily travel sewing kit childrens cutl...
1112,18260,"['RED RETROSPOT TEA CUP AND SAUCER ', 'PINK BL...",2.550000,red retrospot tea cup and saucer pink blue fel...
1113,18272,"['SET OF 4 JAM JAR MAGNETS', 'RED SPOT CERAMIC...",2.682353,set of jam jar magnets red spot ceramic drawer...
1114,18283,"['CHARLOTTE BAG PINK POLKADOT', 'CHARLOTTE BAG...",2.466931,charlotte bag pink polkadot charlotte bag suki...

In [ ]:
df3 = df3.drop_duplicates(['Rating'], keep='last')
df3 = df3.reset_index()
df3

,index,CustomerID,Description,Rating,Description_clean
0,0,12347,"['PINK DRAWER KNOB ACRYLIC EDWARDIAN', 'GREEN ...",2.538462,pink drawer knob acrylic edwardian green drawe...
1,1,12357,"['PENNY FARTHING BIRTHDAY CARD', 'S/4 CACTI CA...",2.465649,penny farthing birthday card s cacti candles f...
2,3,12360,"['SET 36 COLOUR PENCILS DOLLY GIRL', 'SET OF 2...",2.542636,set colour pencils dolly girl set of vintage c...
3,4,12362,"['JUMBO BAG RED RETROSPOT', 'JUMBO BAG VINTAGE...",2.463504,jumbo bag red retrospot jumbo bag vintage doil...
4,5,12370,"['HEART IVORY TRELLIS LARGE', '3D HEARTS HONE...",2.323353,heart ivory trellis large d hearts honeycomb p...
...,...,...,...,...,...
1007,1110,18245,"['WRAP COWBOYS ', 'ALARM CLOCK BAKELIKE RED '...",2.451977,wrap cowboys alarm clock bakelike red spotty b...
1008,1111,18257,"['VINTAGE DOILY TRAVEL SEWING KIT', 'CHILDRENS...",2.341463,vintage doily travel sewing kit childrens cutl...
1009,1112,18260,"['RED RETROSPOT TEA CUP AND SAUCER ', 'PINK BL...",2.550000,red retrospot tea cup and saucer pink blue fel...
1010,1113,18272,"['SET OF 4 JAM JAR MAGNETS', 'RED SPOT CERAMIC...",2.682353,set of jam jar magnets red spot ceramic drawer...
1011,1114,18283,"['CHARLOTTE BAG PINK POLKADOT', 'CHARLOTTE BAG...",2.466931,charlotte bag pink polkadot charlotte bag suki...

In [ ]:
from pandas import DataFrame
from sklearn.feature_extraction.text import CountVectorizer
docs = df3["Description_clean"]
vect = CountVectorizer(max_features = 100, stop_words='english')
vect

CountVectorizer(max_features=100, stop_words='english')

In [ ]:
X = vect.fit_transform(docs)
X

<1012x100 sparse matrix of type '<class 'numpy.int64'>'
	with 69100 stored elements in Compressed Sparse Row format>

In [ ]:
df5 = DataFrame(X.A, columns=vect.get_feature_names_out())
df5 = df5.astype(int)

In [ ]:
df5

,alarm,antique,assorted,bag,bakelike,bird,birthday,black,blue,bottle,...,wall,warmer,water,white,wicker,wood,wooden,woodland,wrap,zinc
0,17,4,3,24,17,0,0,5,3,0,...,0,0,0,4,0,0,3,6,0,0
1,3,0,0,3,3,0,13,7,3,9,...,5,2,7,7,0,0,1,0,0,0
2,0,0,2,7,0,1,3,0,9,0,...,0,0,0,1,0,2,0,6,0,0
3,8,0,2,38,8,1,2,2,6,5,...,2,0,5,2,0,0,4,15,0,0
4,0,1,5,9,0,4,6,1,4,1,...,0,2,1,15,0,2,5,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,3,3,2,2,3,1,9,0,2,3,...,1,1,1,7,1,1,1,3,8,4
1008,0,0,0,35,0,0,0,1,4,0,...,5,0,0,1,2,0,3,1,0,0
1009,0,0,4,1,0,5,5,0,5,0,...,0,0,0,15,0,0,0,0,0,2
1010,0,0,3,0,0,0,0,0,9,1,...,3,0,1,2,0,0,1,3,0,0
1011,0,1,0,358,0,0,1,14,13,0,...,0,0,0,6,2,3,15,47,7,1

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo,Offer,Day_Name
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2,1,0,15,Wednesday
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,4,0,1,No offer,Wednesday
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,4,1,0,10,Wednesday
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,5,1,0,Buy one get one,Wednesday
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,1,1,0,25,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France,2,1,0,Buy one get one,Friday
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France,5,0,1,20,Friday
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France,2,1,0,15,Friday
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France,0,1,0,20,Friday
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France,3,1,0,20,Friday

In [ ]:
kkk=df.sort_values(by='Rating', ascending=False)
kkk  = df.drop_duplicates(['Description'], keep='first') #Keeping the best rating product by arranging in descending order
kkk = kkk.reset_index()

In [ ]:
kkk

,index,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Rating,used_Discount,used_bogo,Offer,Day_Name
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,2,1,0,15,Wednesday
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,4,0,1,No offer,Wednesday
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,4,1,0,10,Wednesday
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,5,1,0,Buy one get one,Wednesday
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,1,1,0,25,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3891,527067,580691,90214W,"LETTER ""W"" BLING KEY RING",12,2011-12-05 15:48:00,0.29,13790,United Kingdom,3,1,0,20,Monday
3892,527069,580691,90214Z,"LETTER ""Z"" BLING KEY RING",12,2011-12-05 15:48:00,0.29,13790,United Kingdom,5,0,1,Buy one get one,Monday
3893,530382,580865,90089,PINK CRYSTAL SKULL PHONE CHARM,12,2011-12-06 11:58:00,0.19,17914,United Kingdom,3,0,1,20,Tuesday
3894,537621,581334,85123A,CREAM HANGING HEART T-LIGHT HOLDER,4,2011-12-08 12:07:00,2.95,17841,United Kingdom,3,0,1,10,Thursday
3895,540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446,United Kingdom,4,0,1,No offer,Friday

In [ ]:
df5

,alarm,antique,assorted,bag,bakelike,bird,birthday,black,blue,bottle,...,wall,warmer,water,white,wicker,wood,wooden,woodland,wrap,zinc
0,17,4,3,24,17,0,0,5,3,0,...,0,0,0,4,0,0,3,6,0,0
1,3,0,0,3,3,0,13,7,3,9,...,5,2,7,7,0,0,1,0,0,0
2,0,0,2,7,0,1,3,0,9,0,...,0,0,0,1,0,2,0,6,0,0
3,8,0,2,38,8,1,2,2,6,5,...,2,0,5,2,0,0,4,15,0,0
4,0,1,5,9,0,4,6,1,4,1,...,0,2,1,15,0,2,5,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,3,3,2,2,3,1,9,0,2,3,...,1,1,1,7,1,1,1,3,8,4
1008,0,0,0,35,0,0,0,1,4,0,...,5,0,0,1,2,0,3,1,0,0
1009,0,0,4,1,0,5,5,0,5,0,...,0,0,0,15,0,0,0,0,0,2
1010,0,0,3,0,0,0,0,0,9,1,...,3,0,1,2,0,0,1,3,0,0
1011,0,1,0,358,0,0,1,14,13,0,...,0,0,0,6,2,3,15,47,7,1

In [ ]:
X = np.array(df5)
X

array([[17,  4,  3, ...,  6,  0,  0],
       [ 3,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  2, ...,  6,  0,  0],
       ...,
       [ 0,  0,  4, ...,  0,  0,  2],
       [ 0,  0,  3, ...,  3,  0,  0],
       [ 0,  1,  0, ..., 47,  7,  1]])

In [ ]:
tpercent = 0.95
tsize = int(np.floor(tpercent * len(df5)))
tsize

961

In [ ]:
df5_train = X[:tsize]

df5_test = X[tsize:]

lentrain = len(df5_train)
lentest = len(df5_test)

In [ ]:
lentrain

961

In [ ]:
lentest

51

In [ ]:
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(df5_train)

In [ ]:
nbrs

NearestNeighbors(algorithm='ball_tree', n_neighbors=3)

In [ ]:
distances, indices = nbrs.kneighbors(df5_train)

In [ ]:
distances

array([[  0.        ,  44.94441011,  47.16990566],
       [  0.        ,  36.0970913 ,  37.05401463],
       [  0.        ,  33.07567082,  33.51119216],
       ...,
       [  0.        ,  22.737634  ,  23.04343724],
       [  0.        , 109.15127118, 116.18519699],
       [  0.        ,  34.98571137,  36.20773398]])

In [ ]:
indices

array([[  0,  64, 416],
       [  1,  48, 135],
       [  2, 353,   7],
       ...,
       [958, 785, 842],
       [959, 716, 824],
       [960, 639, 281]])

In [ ]:
a = nbrs.kneighbors([df5_test[0]])

In [ ]:
a

(array([[101.19782606, 107.60576193, 109.05044704]]), array([[734, 581, 542]]))

In [ ]:
related_product_list = a[1]
related_product_list

array([[734, 581, 542]])

In [ ]:
first_related_product = [item[0] for item in related_product_list]
first_related_product = str(first_related_product).strip('[]')
first_related_product = int(first_related_product)

In [ ]:
first_related_product

734

In [ ]:
for i in range(lentest):
    a = nbrs.kneighbors([df5_test[i]])
    related_product_list = a[1]

    first_related_product = [item[0] for item in related_product_list]
    first_related_product = str(first_related_product).strip('[]')
    first_related_product = int(first_related_product)
    second_related_product = [item[1] for item in related_product_list]
    second_related_product = str(second_related_product).strip('[]')
    second_related_product = int(second_related_product)
    third_related_product = [item[2] for item in related_product_list]
    third_related_product = str(third_related_product).strip('[]')
    third_related_product = int(third_related_product)

    print ("Based on  description, for user is ", df3["CustomerID"][lentrain + i])

    for i in range(3896):
      if (kkk["CustomerID"][i] == df3["CustomerID"][first_related_product]):
        print ("The first similar user is ", df3["CustomerID"][first_related_product], ".")
        print ("He/She likes following products")
        for i in range(3896):
            if (kkk["CustomerID"][i] == df3["CustomerID"][first_related_product]):
                aaa= kkk["StockCode"][i]
                bbb= kkk["Rating"][i]

                print(aaa ," and it's rating is : ", bbb)
        print ("--------------------------------------------------------------------")
        break

        #print("_________")
    for i in range(3896):
      if (kkk["CustomerID"][i] == df3["CustomerID"][second_related_product]):
        print ("The second similar user is ", df3["CustomerID"][second_related_product], ".")
        print ("He/She likes following products")
        for i in range(3896):
            if (kkk["CustomerID"][i] == df3["CustomerID"][second_related_product]):
                aaa= kkk["StockCode"][i]
                bbb=kkk["Rating"][i]

                print(aaa ," and it's rating is : ", bbb)
        print ("--------------------------------------------------------------------")
        break

    for i in range(3896):
      if (kkk["CustomerID"][i] == df3["CustomerID"][third_related_product]):
        print ("The third similar user is ", df3["CustomerID"][third_related_product], ".")
        print ("He/She likes following products")
        for i in range(3896):
            if (kkk["CustomerID"][i] == df3["CustomerID"][third_related_product]):
                aaa= kkk["StockCode"][i]
                bbb=kkk["Rating"][i]

                print(aaa ," and it's rating is : ", bbb)
        print ("--------------------------------------------------------------------")
        break



    print ("--------------------------------------------------------------------")

Based on  description, for user is  17954
The first similar user is  16745 .
He/She likes following products
84568  and it's rating is :  1
84598  and it's rating is :  0
23321  and it's rating is :  3
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  17961
The second similar user is  13764 .
He/She likes following products
21278  and it's rating is :  0
--------------------------------------------------------------------
The third similar user is  15281 .
He/She likes following products
21280  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  17964
--------------------------------------------------------------------
Based on  description, for user is  17965
The first similar user is  17419 .
He/She likes following products
21773  and it's rating is :  0
--------------------------------------------------------------------
The third similar user is  14461 .
He/She likes following products
90036F  and it's rating is :  5
90030B  and it's rating is :  1
90131  and it's rating is :  5
84551  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  17974
--------------------------------------------------------------------
Based on  description, for user is  17975
The second similar user is  13168 .
He/She likes following products
35638A  and it's rating is :  2
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  17979
The first similar user is  15987 .
He/She likes following products
22811  and it's rating is :  0
21713  and it's rating is :  3
20802  and it's rating is :  1
22052  and it's rating is :  0
20781  and it's rating is :  1
22389  and it's rating is :  4
90014C  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  17997
The third similar user is  14626 .
He/She likes following products
23484  and it's rating is :  3
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18016
The first similar user is  17897 .
He/She likes following products
21621  and it's rating is :  3
47563A  and it's rating is :  5
84558A  and it's rating is :  1
21577  and it's rating is :  5
22087  and it's rating is :  4
22651  and it's rating is :  5
22713  and it's rating is :  0
21370  and it's rating is :  5
21367  and it's rating is :  4
22376  and it's rating is :  3
21895  and it's rating is :  0
22372  and it's rating is :  4
21190  and it's rating is :  2
21894  and it's rating is :  3
70007  and it's rating is :  1
84596J  and it's rating is :  0
85170A  and it's rating is :  3
85059  and it's rating is :  4
84497  and it's rating is :  2
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18022
The third similar user is  13654 .
He/She likes following products
90093  and it's rating is :  1
90085  and it's rating is :  2
23475  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18034
--------------------------------------------------------------------
Based on  description, for user is  18041
The first similar user is  12720 .
He/She likes following products
22346  and it's rating is :  2
22344  and it's rating is :  2
22345  and it's rating is :  1
--------------------------------------------------------------------
The second similar user is  12766 .
He/She likes following products
22513  and it's rating is :  3
71496A  and it's rating is :  3
71495B  and it's rating is :  1
78124  and it's rating is :  4
--------------------------------------------------------------------
The third similar user is  16873 .
He/She likes following products
85230E  and it's rating is :  4
22826  and it's rating is :  2
22852  and it's rating is :  3
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18043
--------------------------------------------------------------------
Based on  description, for user is  18044
The first similar user is  16293 .
He/She likes following products
23085  and it's rating is :  5
--------------------------------------------------------------------
The second similar user is  17897 .
He/She likes following products
21621  and it's rating is :  3
47563A  and it's rating is :  5
84558A  and it's rating is :  1
21577  and it's rating is :  5
22087  and it's rating is :  4
22651  and it's rating is :  5
22713  and it's rating is :  0
21370  and it's rating is :  5
21367  and it's rating is :  4
22376  and it's rating is :  3
21895  and it's rating is :  0
22372  and it's rating is :  4
21190  and it's rating is :  2
21894  and it's rating is :  3
70007  and it's rating is :  1
84596J  and it's rating is :  0
85170A  and it's rating is :  3
85059  and it's rating is :  4
84497  and it's rating is :  2
--------------------------------------------------------------------
The third similar user is  17043 .
He/She likes following products
84828  and it's rating is :  4
21243  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18055
The third similar user is  13124 .
He/She likes following products
84929  and it's rating is :  1
17012C  and it's rating is :  2
21194  and it's rating is :  0
21792  and it's rating is :  3
35649  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18065
The third similar user is  16912 .
He/She likes following products
23092  and it's rating is :  2
23457  and it's rating is :  0
23456  and it's rating is :  0
23455  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18069
The first similar user is  17613 .
He/She likes following products
20694  and it's rating is :  4
--------------------------------------------------------------------
The third similar user is  16327 .
He/She likes following products
35653  and it's rating is :  4
85130D  and it's rating is :  1
15039  and it's rating is :  3
84978  and it's rating is :  0
84569D  and it's rating is :  0
72351A  and it's rating is :  4
84921  and it's rating is :  3
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18075
The second similar user is  13782 .
He/She likes following products
23472  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18077
--------------------------------------------------------------------
Based on  description, for user is  18079
The second similar user is  17864 .
He/She likes following products
23390  and it's rating is :  4
23389  and it's rating is :  0
--------------------------------------------------------------------
The third similar user is  16607 .
He/She likes following products
90209C  and it's rating is :  4
16156L  and it's rating is :  0
16169E  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18096
The third similar user is  15862 .
He/She likes following products
22110  and it's rating is :  2
22098  and it's rating is :  5
22100  and it's rating is :  1
22766  and it's rating is :  4
22451  and it's rating is :  4
22549  and it's rating is :  5
84744  and it's rating is :  0
85049E  and it's rating is :  1
21328  and it's rating is :  2
17091A  and it's rating is :  5
22473  and it's rating is :  1
84509A  and it's rating is :  0
84510A  and it's rating is :  0
22767  and it's rating is :  5
22768  and it's rating is :  3
21463  and it's rating is :  4
21464  and it's rating is :  5
20820  and it's rating is :  5
85150  and it's rating is :  1
22117  and it's rating is :  4
48129  and it's rating is :  1
82580  and it's rating is :  2
82578  and it's rating is :  2
82581  and it's rating is :  3
22413  and it's rating is :  1
21907  and it's rating is :  0
22441  and it's rating is :  1
21122  and it's rating is :  0
22851  and it's rating is :  1
22810  and it's rating is :  1
22809  and it's rating is :  5
22435  and it's rating is :  0
20966  and it's rating is :  5
20963  and it's rating is :  4
20961  and it's rating is :  2
22068  and it's rating is :  0
21743  and it's rating is :  1
21744  and it's rating is :  0
84709B  and it's rating is :  0
21592  and it's rating is :  1
21587  and it's rating is :  3
20992  and it's rating is :  4
22804  and it's rating is :  5
20749  and it's rating is :  0
22382  and it's rating is :  2
20726  and it's rating is :  0
22384  and it's rating is :  4
22467  and it's rating is :  5
84625C  and it's rating is :  5
84625A  and it's rating is :  5
21108  and it's rating is :  1
22848  and it's rating is :  5
47570B  and it's rating is :  5
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18097
The first similar user is  13659 .
He/She likes following products
71101E  and it's rating is :  4
--------------------------------------------------------------------
The second similar user is  12556 .
He/She likes following products
35645  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18102
The second similar user is  13742 .
He/She likes following products
21317  and it's rating is :  1
22785  and it's rating is :  2
23247  and it's rating is :  1
--------------------------------------------------------------------
The third similar user is  15044 .
He/She likes following products
21793  and it's rating is :  1
23099  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18109
The first similar user is  17576 .
He/She likes following products
22734  and it's rating is :  1
47578A  and it's rating is :  1
35095B  and it's rating is :  5
35095A  and it's rating is :  2
--------------------------------------------------------------------
The third similar user is  17813 .
He/She likes following products
23461  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18116
The second similar user is  13869 .
He/She likes following products
85232A  and it's rating is :  1
23330  and it's rating is :  1
--------------------------------------------------------------------
The third similar user is  14701 .
He/She likes following products
90084  and it's rating is :  0
22286  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18118
The first similar user is  17511 .
He/She likes following products
22962  and it's rating is :  1
22963  and it's rating is :  4
22968  and it's rating is :  4
84970S  and it's rating is :  5
22910  and it's rating is :  4
20668  and it's rating is :  1
22197  and it's rating is :  2
22198  and it's rating is :  3
21080  and it's rating is :  1
21086  and it's rating is :  0
21786  and it's rating is :  2
22654  and it's rating is :  5
21485  and it's rating is :  2
84030E  and it's rating is :  2
22174  and it's rating is :  0
22257  and it's rating is :  4
22258  and it's rating is :  0
22259  and it's rating is :  2
23547  and it's rating is :  1
23548  and it's rating is :  4
23501  and it's rating is :  0
23692  and it's rating is :  1
--------------------------------------------------------------------
The second similar user is  14156 .
He/She likes following products
17084R  and it's rating is :  5
17091J  and it's rating is :  0
22967  and it's rating is :  3
22957  and it's rating is :  5
22896  and it's rating is :  2
22199  and it's rating is :  5
20914  and it's rating is :  5
20725  and it's rating is :  3
23010  and it's rating is :  4
23032  and it's rating is :  4
23028  and it's rating is :  5
23271  and it's rating is :  5
23131  and it's rating is :  5
23360  and it's rating is :  0
23236  and it's rating is :  2
23413  and it's rating is :  3
23409  and it's rating is :  3
--------------------------------------------------------------------
The third similar user is  13081 .
He/She likes following products
22348  and it's rating is :  5
20829  and it's rating is :  2
21224  and it's rating is :  3
21721  and it's rating is :  2
84988  and it's rating is :  4
21947  and it's rating is :  1
21726  and it's rating is :  4
22200  and it's rating is :  4
79320  and it's rating is :  2
85042  and it's rating is :  3
22182  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18122
The second similar user is  16016 .
He/She likes following products
20763  and it's rating is :  2
23283  and it's rating is :  5
90201D  and it's rating is :  2
90201C  and it's rating is :  0
90201A  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18125
The first similar user is  16898 .
He/She likes following products
21219  and it's rating is :  2
84596B  and it's rating is :  4
21226  and it's rating is :  2
20869  and it's rating is :  4
--------------------------------------------------------------------
The third similar user is  16871 .
He/She likes following products
23212  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18139
--------------------------------------------------------------------
Based on  description, for user is  18145
The third similar user is  15764 .
He/She likes following products
23181  and it's rating is :  5
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18156
The first similar user is  16725 .
He/She likes following products
22509  and it's rating is :  1
21196  and it's rating is :  1
21199  and it's rating is :  2
21641  and it's rating is :  0
--------------------------------------------------------------------
The second similar user is  15373 .
He/She likes following products
90099  and it's rating is :  0
--------------------------------------------------------------------
The third similar user is  13982 .
He/She likes following products
71143  and it's rating is :  3
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18168
The first similar user is  13952 .
He/She likes following products
46776A  and it's rating is :  0
46776F  and it's rating is :  3
46776D  and it's rating is :  3
PADS  and it's rating is :  4
35599D  and it's rating is :  3
--------------------------------------------------------------------
The third similar user is  16725 .
He/She likes following products
22509  and it's rating is :  1
21196  and it's rating is :  1
21199  and it's rating is :  2
21641  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18172
--------------------------------------------------------------------
Based on  description, for user is  18180
The third similar user is  15214 .
He/She likes following products
35966  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18196
The first similar user is  13659 .
He/She likes following products
71101E  and it's rating is :  4
--------------------------------------------------------------------
The third similar user is  14640 .
He/She likes following products
23015  and it's rating is :  2
23024  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18198
The first similar user is  16818 .
He/She likes following products
21015  and it's rating is :  2
23214  and it's rating is :  5
23215  and it's rating is :  1
--------------------------------------------------------------------
The third similar user is  13782 .
He/She likes following products
23472  and it's rating is :  1
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18204
The first similar user is  15012 .
He/She likes following products
84997D  and it's rating is :  5
47599A  and it's rating is :  1
47599B  and it's rating is :  0
20972  and it's rating is :  2
21041  and it's rating is :  5
21664  and it's rating is :  4
22907  and it's rating is :  2
22776  and it's rating is :  3
21810  and it's rating is :  3
21197  and it's rating is :  4
85035B  and it's rating is :  0
84968C  and it's rating is :  2
21098  and it's rating is :  1
21192  and it's rating is :  4
72800B  and it's rating is :  0
84563A  and it's rating is :  2
47504H  and it's rating is :  0
21742  and it's rating is :  3
22481  and it's rating is :  2
--------------------------------------------------------------------
The second similar user is  15549 .
He/She likes following products
85188A  and it's rating is :  1
23320  and it's rating is :  0
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18210
The first similar user is  16284 .
He/She likes following products
23499  and it's rating is :  4
--------------------------------------------------------------------
The third similar user is  12743 .
He/She likes following products
85179C  and it's rating is :  4
--------------------------------------------------------------------
--------------------------------------------------------------------
Based on  description, for user is  18219